server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: autofix-autos
          uri: lb://AUTOFIX-AUTOS
          predicates:
            - Path=/api/autos/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}
        - id: autofix-marcas
          uri: lb://AUTOFIX-AUTOS
          predicates:
            - Path=/api/marcas/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}
        - id: autofix-reparaciones
          uri: lb://AUTOFIX-REPARACIONES
          predicates:
            - Path=/api/reparaciones/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}
        - id: autofix-ordenes
          uri: lb://AUTOFIX-ORDENES
          predicates:
            - Path=/api/ordenes/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}
        - id: autofix-bonos
          uri: lb://AUTOFIX-ORDENES
          predicates:
            - Path=/api/bonos/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}
        - id: autofix-reportes
          uri: lb://AUTOFIX-REPORTES
          predicates:
            - Path=/api/reportes/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}