server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: autofix-autos
          uri: lb://autofix-autos:8090
          predicates:
            - Path=/marcas/**
        - id: autofix-reparaciones
          uri: lb://autofix-reparaciones:8091
          predicates:
            - Path=/reparaciones/**
        - id: autofix-ordenes
          uri: lb://autofix-ordenes:8092
          predicates:
            - Path=/ordenes/**
        - id: autofix-reportes
          uri: lb://autofix-reportes:8093
          predicates:
            - Path=/reportes/**