server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG
    org.springframework.http: DEBUG
    org.springframework.core.codec: DEBUG
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: autofix-autos
          uri: lb://AUTOFIX-AUTOS
          predicates:
            - Path=/autos/**
          filters:
            - RewritePath=/autos/(?<segment>.*), /autos/${segment}
        - id: autofix-marcas
          uri: lb://AUTOFIX-AUTOS
          predicates:
            - Path=/marcas/**
          filters:
            - RewritePath=/marcas/(?<segment>.*), /marcas/${segment}

        - id: autofix-reparaciones
          uri: lb://AUTOFIX-REPARACIONES
          predicates:
            - Path=/reparaciones/**
          filters:
            - RewritePath=/reparaciones/(?<segment>.*), /reparaciones/${segment}

        - id: autofix-ordenes
          uri: lb://AUTOFIX-ORDENES
          predicates:
            - Path=/ordenes/**
          filters:
            - RewritePath=/ordenes/(?<segment>.*), /ordenes/${segment}
        - id: autofix-bonos
          uri: lb://AUTOFIX-ORDENES
          predicates:
            - Path=/bonos/**
          filters:
            - RewritePath=/bonos/(?<segment>.*), /bonos/${segment}

        - id: autofix-reportes
          uri: lb://AUTOFIX-REPORTES
          predicates:
            - Path=/reportes/**
          filters:
            - RewritePath=/reportes/(?<segment>.*), /reportes/${segment}
