apiVersion: apps/v1
kind: Deployment
metadata:
  name: autofix-ordenes-deployment
  labels:
    app: autofix-ordenes-deployment
spec:
  selector:
    matchLabels:
      app: autofix-ordenes-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: autofix-ordenes-deployment
    spec:
      containers:
        - name: autofix-ordenes
          image: estebanglochon/autofix-service-ordenes
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "8092"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_ORDENES
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_ORDENES
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_ORDENES
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_ORDENES
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_ORDENES
---
apiVersion: v1
kind: Service
metadata:
  name: autofix-ordenes-service
  labels:
    app: autofix-ordenes-service
spec:
  selector:
    app: autofix-ordenes-deployment
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: LoadBalancer