apiVersion: apps/v1
kind: Deployment
metadata:
  name: autofix-reparaciones-deployment
  labels:
    app: autofix-reparaciones-deployment
spec:
  selector:
    matchLabels:
      app: autofix-reparaciones-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: autofix-reparaciones-deployment
    spec:
      containers:
        - name: autofix-reparaciones
          image: estebanglochon/autofix-service-reparaciones
          ports:
            - containerPort: 8091
          env:
            - name: TZ
              value: America/Santiago
            - name: SERVER_PORT
              value: "8091"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REPARACIONES
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REPARACIONES
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_REPARACIONES
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REPARACIONES
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REPARACIONES
---
apiVersion: v1
kind: Service
metadata:
  name: autofix-reparaciones-service
  labels:
    app: autofix-reparaciones-service
spec:
  selector:
    app: autofix-reparaciones-deployment
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: LoadBalancer