apiVersion: apps/v1
kind: Deployment
metadata:
  name: autofix-reportes-deployment
  labels:
    app: autofix-reportes-deployment
spec:
  selector:
    matchLabels:
      app: autofix-reportes-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: autofix-reportes-deployment
    spec:
      containers:
        - name: autofix-reportes
          image: estebanglochon/autofix-service-reportes
          ports:
            - containerPort: 8093
          env:
            - name: SERVER_PORT
              value: "0"