apiVersion: apps/v1
kind: Deployment
metadata:
  name: autofix-autos-deployment
  labels:
    app: autofix-autos-deployment
spec:
  selector:
    matchLabels:
      app: autofix-autos-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: autofix-autos-deployment
    spec:
      containers:
        - name: autofix-autos
          image: estebanglochon/autofix-service-autos
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "8090"
            - name: TZ
              value: America/Santiago
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_AUTOS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_AUTOS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_AUTOS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_AUTOS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_AUTOS
---
apiVersion: v1
kind: Service
metadata:
  name: autofix-autos-service
  labels:
    app: autofix-autos-service
spec:
  selector:
    app: autofix-autos-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer