apiVersion: apps/v1
kind: Deployment
metadata:
  name: autofix-frontend-deployment
  labels:
    app: autofix-frontend-deployment
spec:
  selector:
    matchLabels:
      app: autofix-frontend-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: autofix-frontend-deployment
    spec:
      containers:
        - name: autofix-frontend
          image: estebanglochon/autofix-service-frontend
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: America/Santiago
            - name: BACKEND_URI
              value: "http://gateway-server-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: autofix-frontend-service
  labels:
    app: autofix-frontend-service
spec:
  selector:
    app: autofix-frontend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300
  type: LoadBalancer