apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_AUTOS: autos-db-service
  DB_PORT_AUTOS: "5432"
  DB_DBNAME_AUTOS: autos-db
  DB_HOST_REPARACIONES: reparaciones-db-service
  DB_PORT_REPARACIONES: "5433"
  DB_DBNAME_REPARACIONES: reparaciones-db
  DB_HOST_ORDENES: ordenes-db-service
  DB_PORT_ORDENES: "5434"
  DB_DBNAME_ORDENES: ordenes-db