#!/bin/bash

wait_for_pod_running() {
  local pod_name=$1
  local timeout=30
  local interval=2
  local elapsed=0

  echo "Waiting for pod '$pod_name' to be in 'Running' state..."

  while true; do
    # Get the current status of the pod
    status=$(minikube kubectl -- get pods | grep "$pod_name")

    # Check if the pod is in "Running" state
    if echo "$status" | grep "Running"; then
      echo "Pod '$pod_name' is in 'Running' state."
      return 0
    fi

    # Check if the timeout has been reached
    if (( elapsed >= timeout )); then
      echo "Timeout reached: Pod '$pod_name' is not in 'Running' state after $timeout seconds."
      return 1
    fi

    # Wait for the specified interval before checking again
    sleep "$interval"
    elapsed=$((elapsed + interval))
  done
}

minikube kubectl -- apply -f postgres-config-map.yaml
minikube kubectl -- apply -f postgres-secrets.yaml

minikube kubectl -- apply -f config-server-deployment-service.yaml
wait_for_pod_running config-server-deployment
minikube kubectl -- apply -f eureka-server-deployment-service.yaml
wait_for_pod_running eureka-server-deployment

minikube kubectl -- apply -f autos-db-deployment-service.yaml
minikube kubectl -- apply -f reparaciones-db-deployment-service.yaml
minikube kubectl -- apply -f ordenes-db-deployment-service.yaml
wait_for_pod_running autos-db-deployment
wait_for_pod_running reparaciones-db-deployment
wait_for_pod_running ordenes-db-deployment

minikube kubectl -- apply -f autofix-autos-deployment-service.yaml
wait_for_pod_running autofix-autos-deployment
minikube kubectl -- apply -f autofix-reparaciones-deployment-service.yaml
wait_for_pod_running autofix-reparaciones-deployment
minikube kubectl -- apply -f autofix-ordenes-deployment-service.yaml
wait_for_pod_running autofix-ordenes-deployment
minikube kubectl -- apply -f autofix-reportes-deployment-service.yaml
wait_for_pod_running autofix-reportes-deployment

minikube kubectl -- apply -f gateway-server-deployment-service.yaml
wait_for_pod_running gateway-server-deployment

minikube kubectl -- apply -f autofix-frontend-deployment-service.yaml
wait_for_pod_running autofix-frontend-deployment
